import localFont from "next/font/local";
import "./globals.css";

// Import ฟอนต์แบบ local ด้วยการใช้ custom properties
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900", // กำหนดน้ำหนักฟอนต์
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// ข้อมูล metadata สำหรับเว็บไซต์
export const metadata = {
  title: "Create Next App", // ชื่อของเว็บไซต์ที่ดูน่าสนใจยิ่งขึ้น
  description: "Generated by create next app", // คำบรรยายที่บอกถึงความสวยงาม
};

// ฟังก์ชันสำหรับ Layout หลักของเว็บไซต์
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="icon" href="/favicon.ico" /> {/* เพิ่ม favicon */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 text-gray-800 min-h-screen flex flex-col`} // ปรับให้ครอบคลุมทั้งหน้าจอ
      >
        {/* Container หลักแบบเต็มจอ */}
        <div className="flex flex-col min-h-screen w-full">
          {/* Content section */}
          <main className="flex-grow w-full px-4 py-8 flex items-center justify-center">
            {children} {/* แสดงผลเนื้อหาที่ถูกส่งเข้ามา */}
          </main>

          {/* Footer ติดขอบล่างสุดของหน้าจอ */}
          <footer className="w-full bg-gray-800 text-white py-4 text-center mt-auto">
            <p>© 2024 My Full-Screen App. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}